services:
  svc-identity:
    build:
      context: /mnt/oz-backend/Src/
      dockerfile: Identity.Dockerfile
    image: svc-identity
    container_name: svc-identity
    hostname: svc-identity
    restart: unless-stopped
    expose:
      - 80
    networks:
      - npm



networks:
  npm:
    external: true
