services:
  svc-configuration:
    build:
      context: /mnt/oz-backend/Src/
      dockerfile: Configuration.Dockerfile
    image: svc-configuration
    container_name: svc-configuration
    hostname: svc-configuration
    restart: unless-stopped
    expose:
      - 80
    networks:
      - npm



networks:
  npm:
    external: true
